name: Rust Build and Release

on:
  push:
    branches:
      - release
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu, target=x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin

    - name: Build project for Linux
      run: cargo build --release --target=x86_64-unknown-linux-gnu

    - name: Build project for Windows
      run: cargo build --release --target=x86_64-pc-windows-msvc
      shell: bash

    - name: Build project for macOS
      run: cargo build --release --target=x86_64-apple-darwin

    - name: Build project for ARM macOS
      run: cargo build --release --target=aarch64-apple-darwin

    - name: Package Linux artifact
      run: tar -czf linux_build.tar.gz target/x86_64-unknown-linux-gnu/release/your_project_name

    - name: Package Windows artifact
      run: zip -r windows_build.zip target/x86_64-pc-windows-msvc/release/your_project_name.exe

    - name: Package macOS artifact
      run: tar -czf macos_build.tar.gz target/x86_64-apple-darwin/release/your_project_name

    - name: Package ARM macOS artifact
      run: tar -czf arm_macos_build.tar.gz target/aarch64-apple-darwin/release/your_project_name

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux_build.tar.gz
          windows_build.zip
          macos_build.tar.gz
          arm_macos_build.tar.gz
        token: ${{ secrets.ROBIN_TOKEN }}
