name: Rust Build and Release

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.1.1'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    outputs:
      outout: ${{ steps.artifact-up.outputs.artifact-id }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build project for Linux
      run: cargo build --release
    
    - name: Upload linux artifact
      uses: actions/upload-artifact@v4
      id: artifact-up
      with:
        name: robin_ubuntu
        path: target/release/robin

  build-windows:
    runs-on: windows-latest

    outputs:
      outout: ${{ steps.artifact-up.outputs.artifact-id }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build project for Windows
      run: cargo build --release
    
    - name: Upload windows artifact
      uses: actions/upload-artifact@v4
      id: artifact-up
      with:
        name: robin_windows
        path: target/release/robin.exe

  build-darwin:
    runs-on: macos-latest

    outputs:
      outout: ${{ steps.artifact-up.outputs.artifact-id }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build project for Darwin
      run: cargo build --release

    - name: Upload darwin artifact
      uses: actions/upload-artifact@v4
      id: artifact-up
      with:
        name: robin_darwin
        path: target/release/robin

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows, build-darwin]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Install zip
        run: sudo apt install zip

      - name: Zip Ubuntu
        run: zip -r ubuntu_release.zip robin_ubuntu
      
      - name: Zip Windows
        run: zip -r windows_release.zip robin_windows

      - name: Zip Darwin
        run: zip -r darwin_release.zip robin_darwin

      - name: Display structure of files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          body: "Automated builds!!! Yeey!!!"
          prerelease: true
          draft: true
          make_latest: "true"
          files: |
            ubuntu_release.zip
            windows_release.zip
            darwin_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ROBIN_TOKEN }}